name: android beta code push

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'release notes'
        required: false
        default: 'code push'

env:
  NODE_VERSION: 16.x
  GIT_AUTHORIZATION: ${{ secrets.GH_TOKEN }}
  CACHE_NODE_MODULE: node_modules@v1
  DEPLOYMENT_NAME: dev-lycl/template-android

jobs:
  init:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

  deploy:
    name: Deploy
    runs-on: macOS-latest
    needs: [init]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-${{ hashFiles('**/package-lock.json') }}

      - name: Code Push
        env:
          RELEASE_NOTE: ${{ github.event.inputs.release_notes }}
        run: |
          appcenter codepush release-react -a ${{ env.DEPLOYMENT_NAME }} -d Staging --description "${{ env.RELEASE_NOTE }}" --token ${{ secrets.APPCENTER_ACCESS_TOKEN }}
